name: career_portfolio
channels:
  - conda-forge
dependencies:
  - conda
  - pip
  - python-graphviz
  - graphviz
  - matplotlib
  - numpy
  - pandas
  - plotly
  - requests
  - streamlit
  - typing-extensions
  - pip:
    - streamlit_timeline
    - streamlit-player